### ISSUE TITLE
Doesn't work and is outdated:: needs to updated to HA 2024.11.x (and soon 2024.12.x)

### ISSUE THREAD

**Issue by devinhedge** [iantrich/text-divider-row#39]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Core: 2024.11.3
Supervisor: 2024.11.4
Operating System: 13.2
Frontend: 20241106.2

**Last working release (if known):**
Don't know. My guess wouldd be 2023.10.4

**Browser and Operating System:**

Firefox 132.0.2 (aarch64) on MacOS 15.1.1 (24B91)
Brave v1.73.91 on Windows 10 (AMD Ryzen 5, 3rd Gen)

**Description of problem:**

It just doesn't work. 

![image](https://github.com/user-attachments/assets/ec264109-ec12-4c04-83e6-cb1a034fb36f)

**Javascript errors shown in the web inspector (if applicable):**

```
lockdown-install.js:1 Removing unpermitted intrinsics
auto-entities.js?hacstag=1677445841130:172 AUTO-ENTITIES 1.13.0 IS INSTALLED
button-card.js?hacstag=146194325412:426   BUTTON-CARD   Version 4.1.2 
bubble-card.js?hacstag=680112919224:1201  Bubble Card  v2.2.4 
vertical-stack-in-card.js?hacstag=142051833050:1 vertical-stack-in-cardVersion: 0.4.4
simple-thermostat.js?hacstag=158654878250:292 simple-thermostat: 2.5.0
alarmo-card.js?hacstag=391372854152:858   ALARMO-CARD    Version: v1.5.2 
custom-icons.js?hacstag=491465538037:309   Custom-icons    Version 0.3.7 20221004
mushroom-strategy.js?hacstag=619284862210:1  Mushroom Strategy  v2.1.0 
text-divider-row.js?hacstag=179788256141:187   TEXT-DIVIDER-ROW    Version 1.4.1     
mini-graph-card-bundle.js?hacstag=1512800620121:1  MINI-GRAPH-CARD  0.12.1 
create-element-base.ts:252 card custom:text-divider-row Error: Error in card configuration.
    at tt.setConfig (text-divider-row.js?hacstag=179788256141:187:2392)
    at r (create-element-base.ts:153:11)
    at create-element-base.ts:179:12
    at h (create-element-base.ts:285:12)
    at c (create-element-base.ts:242:12)
    at Module.g (create-card-element.ts:105:3)
    at createThing (vertical-stack-in-card.js?hacstag=142051833050:76:31)
    at VerticalStackInCard.createCardElement (vertical-stack-in-card.js?hacstag=142051833050:99:21)
    at vertical-stack-in-card.js?hacstag=142051833050:25:56
    at Array.map (<anonymous>)
c @ create-element-base.ts:252
g @ create-card-element.ts:105
createThing @ vertical-stack-in-card.js?hacstag=142051833050:76
createCardElement @ vertical-stack-in-card.js?hacstag=142051833050:99
(anonymous) @ vertical-stack-in-card.js?hacstag=142051833050:25
renderCard @ vertical-stack-in-card.js?hacstag=142051833050:25
await in renderCard
setConfig @ vertical-stack-in-card.js?hacstag=142051833050:17
r @ create-element-base.ts:153
(anonymous) @ create-element-base.ts:179
h @ create-element-base.ts:285
c @ create-element-base.ts:242
g @ create-card-element.ts:105
value @ hui-card.ts:123
(anonymous) @ hui-card.ts:152
n @ fire_event.ts:76
(anonymous) @ create-element-base.ts:198
Promise.then
(anonymous) @ create-element-base.ts:196
h @ create-element-base.ts:285
c @ create-element-base.ts:242
g @ create-card-element.ts:105
value @ hui-card.ts:123
value @ hui-card.ts:42
value @ hui-section.ts:70
(anonymous) @ hui-section.ts:277
value @ hui-section.ts:276
value @ hui-section.ts:198
value @ hui-section.ts:98
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
i @ hui-section.ts:37
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hui-view.ts:109
(anonymous) @ hui-view.ts:338
value @ hui-view.ts:337
value @ hui-view.ts:242
value @ hui-view.ts:156
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
i @ hui-view.ts:62
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hui-root.ts:937
(anonymous) @ hui-root.ts:611
setTimeout
(anonymous) @ render-status.ts:2
requestAnimationFrame
n @ render-status.ts:2
value @ hui-root.ts:611
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
C @ lit-element.ts:115
o @ hui-root.ts:105
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ ha-panel-lovelace.ts:319
await in value
value @ ha-panel-lovelace.ts:170
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
C @ lit-element.ts:115
o @ ha-panel-lovelace.ts:55
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hass-router-page.ts:297
value @ hass-router-page.ts:317
(anonymous) @ hass-router-page.ts:215
Promise.then
value @ hass-router-page.ts:206
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-router-page.ts:285
await in value
value @ partial-panel-resolver.ts:211
value @ partial-panel-resolver.ts:82
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
n @ hass-router-page.ts:49
r @ partial-panel-resolver.ts:38
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
C @ lit-element.ts:115
r @ home-assistant-main.ts:47
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165
(anonymous) @ superPropGet.js:6
value @ home-assistant.ts:97
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ home-assistant.ts:225
await in value
value @ home-assistant.ts:82
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:56
_updateHass @ context-mixin.ts:107
(anonymous) @ connection-mixin.ts:279
r @ store.js:19
(anonymous) @ collection.js:27
Promise.then
u @ collection.js:27
l @ collection.js:29
(anonymous) @ collection.js:54
subscribe @ collection.js:99
S @ config.js:16
(anonymous) @ core.ts:121
Promise.then
(anonymous) @ core.ts:112
mushroom.js?hacstag=444350375420:309 🍄 Mushroom 🍄 - 4.2.0
create-element-base.ts:252 card custom:text-divider-row Error: Error in card configuration.
    at tt.setConfig (text-divider-row.js?hacstag=179788256141:187:2392)
    at r (create-element-base.ts:153:11)
    at create-element-base.ts:179:12
    at h (create-element-base.ts:285:12)
    at c (create-element-base.ts:242:12)
    at Module.g (create-card-element.ts:105:3)
    at createThing (vertical-stack-in-card.js?hacstag=142051833050:76:31)
    at VerticalStackInCard.createCardElement (vertical-stack-in-card.js?hacstag=142051833050:99:21)
    at vertical-stack-in-card.js?hacstag=142051833050:25:56
    at Array.map (<anonymous>)
c @ create-element-base.ts:252
g @ create-card-element.ts:105
createThing @ vertical-stack-in-card.js?hacstag=142051833050:76
createCardElement @ vertical-stack-in-card.js?hacstag=142051833050:99
(anonymous) @ vertical-stack-in-card.js?hacstag=142051833050:25
renderCard @ vertical-stack-in-card.js?hacstag=142051833050:25
await in renderCard
(anonymous) @ vertical-stack-in-card.js?hacstag=142051833050:106
Promise.then
element.addEventListener.once @ vertical-stack-in-card.js?hacstag=142051833050:105
n @ fire_event.ts:76
(anonymous) @ create-element-base.ts:198
Promise.then
(anonymous) @ create-element-base.ts:196
h @ create-element-base.ts:285
c @ create-element-base.ts:242
g @ create-card-element.ts:105
createThing @ vertical-stack-in-card.js?hacstag=142051833050:76
createCardElement @ vertical-stack-in-card.js?hacstag=142051833050:99
(anonymous) @ vertical-stack-in-card.js?hacstag=142051833050:25
renderCard @ vertical-stack-in-card.js?hacstag=142051833050:25
await in renderCard
setConfig @ vertical-stack-in-card.js?hacstag=142051833050:17
r @ create-element-base.ts:153
(anonymous) @ create-element-base.ts:179
h @ create-element-base.ts:285
c @ create-element-base.ts:242
g @ create-card-element.ts:105
value @ hui-card.ts:123
(anonymous) @ hui-card.ts:152
n @ fire_event.ts:76
(anonymous) @ create-element-base.ts:198
Promise.then
(anonymous) @ create-element-base.ts:196
h @ create-element-base.ts:285
c @ create-element-base.ts:242
g @ create-card-element.ts:105
value @ hui-card.ts:123
value @ hui-card.ts:42
value @ hui-section.ts:70
(anonymous) @ hui-section.ts:277
value @ hui-section.ts:276
value @ hui-section.ts:198
value @ hui-section.ts:98
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
i @ hui-section.ts:37
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hui-view.ts:109
(anonymous) @ hui-view.ts:338
value @ hui-view.ts:337
value @ hui-view.ts:242
value @ hui-view.ts:156
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
i @ hui-view.ts:62
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hui-root.ts:937
(anonymous) @ hui-root.ts:611
setTimeout
(anonymous) @ render-status.ts:2
requestAnimationFrame
n @ render-status.ts:2
value @ hui-root.ts:611
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
C @ lit-element.ts:115
o @ hui-root.ts:105
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ ha-panel-lovelace.ts:319
await in value
value @ ha-panel-lovelace.ts:170
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
C @ lit-element.ts:115
o @ ha-panel-lovelace.ts:55
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hass-router-page.ts:297
value @ hass-router-page.ts:317
(anonymous) @ hass-router-page.ts:215
Promise.then
value @ hass-router-page.ts:206
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-router-page.ts:285
await in value
value @ partial-panel-resolver.ts:211
value @ partial-panel-resolver.ts:82
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
n @ hass-router-page.ts:49
r @ partial-panel-resolver.ts:38
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
C @ lit-element.ts:115
r @ home-assistant-main.ts:47
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165
(anonymous) @ superPropGet.js:6
value @ home-assistant.ts:97
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ home-assistant.ts:225
await in value
value @ home-assistant.ts:82
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:56
_updateHass @ context-mixin.ts:107
(anonymous) @ connection-mixin.ts:279
r @ store.js:19
(anonymous) @ collection.js:27
Promise.then
u @ collection.js:27
l @ collection.js:29
(anonymous) @ collection.js:54
subscribe @ collection.js:99
S @ config.js:16
(anonymous) @ core.ts:121
Promise.then
(anonymous) @ core.ts:112
apexcharts-card.js?hacstag=331701152212:835  APEXCHARTS-CARD  v2.1.2 
HA-Firemote.js?hacstag=536329656413:8  🔥 FIREMOTE-CARD 🔥  v4.1.3 installed 
```

```
lockdown-install.js:1 Removing unpermitted intrinsics
auto-entities.js?hacstag=1677445841130:172 AUTO-ENTITIES 1.13.0 IS INSTALLED
button-card.js?hacstag=146194325412:426   BUTTON-CARD   Version 4.1.2 
bubble-card.js?hacstag=680112919224:1201  Bubble Card  v2.2.4 
vertical-stack-in-card.js?hacstag=142051833050:1 vertical-stack-in-cardVersion: 0.4.4
simple-thermostat.js?hacstag=158654878250:292 simple-thermostat: 2.5.0
alarmo-card.js?hacstag=391372854152:858   ALARMO-CARD    Version: v1.5.2 
custom-icons.js?hacstag=491465538037:309   Custom-icons    Version 0.3.7 20221004
mushroom-strategy.js?hacstag=619284862210:1  Mushroom Strategy  v2.1.0 
text-divider-row.js?hacstag=179788256141:187   TEXT-DIVIDER-ROW    Version 1.4.1     
mini-graph-card-bundle.js?hacstag=1512800620121:1  MINI-GRAPH-CARD  0.12.1 
create-element-base.ts:252 card custom:text-divider-row Error: Error in card configuration.
    at tt.setConfig (text-divider-row.js?hacstag=179788256141:187:2392)
    at r (create-element-base.ts:153:11)
    at create-element-base.ts:179:12
    at h (create-element-base.ts:285:12)
    at c (create-element-base.ts:242:12)
    at Module.g (create-card-element.ts:105:3)
    at createThing (vertical-stack-in-card.js?hacstag=142051833050:76:31)
    at VerticalStackInCard.createCardElement (vertical-stack-in-card.js?hacstag=142051833050:99:21)
    at vertical-stack-in-card.js?hacstag=142051833050:25:56
    at Array.map (<anonymous>)
c @ create-element-base.ts:252
g @ create-card-element.ts:105
createThing @ vertical-stack-in-card.js?hacstag=142051833050:76
createCardElement @ vertical-stack-in-card.js?hacstag=142051833050:99
(anonymous) @ vertical-stack-in-card.js?hacstag=142051833050:25
renderCard @ vertical-stack-in-card.js?hacstag=142051833050:25
await in renderCard
setConfig @ vertical-stack-in-card.js?hacstag=142051833050:17
r @ create-element-base.ts:153
(anonymous) @ create-element-base.ts:179
h @ create-element-base.ts:285
c @ create-element-base.ts:242
g @ create-card-element.ts:105
value @ hui-card.ts:123
(anonymous) @ hui-card.ts:152
n @ fire_event.ts:76
(anonymous) @ create-element-base.ts:198
Promise.then
(anonymous) @ create-element-base.ts:196
h @ create-element-base.ts:285
c @ create-element-base.ts:242
g @ create-card-element.ts:105
value @ hui-card.ts:123
value @ hui-card.ts:42
value @ hui-section.ts:70
(anonymous) @ hui-section.ts:277
value @ hui-section.ts:276
value @ hui-section.ts:198
value @ hui-section.ts:98
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
i @ hui-section.ts:37
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hui-view.ts:109
(anonymous) @ hui-view.ts:338
value @ hui-view.ts:337
value @ hui-view.ts:242
value @ hui-view.ts:156
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
i @ hui-view.ts:62
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hui-root.ts:937
(anonymous) @ hui-root.ts:611
setTimeout
(anonymous) @ render-status.ts:2
requestAnimationFrame
n @ render-status.ts:2
value @ hui-root.ts:611
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
C @ lit-element.ts:115
o @ hui-root.ts:105
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ ha-panel-lovelace.ts:319
await in value
value @ ha-panel-lovelace.ts:170
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
C @ lit-element.ts:115
o @ ha-panel-lovelace.ts:55
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hass-router-page.ts:297
value @ hass-router-page.ts:317
(anonymous) @ hass-router-page.ts:215
Promise.then
value @ hass-router-page.ts:206
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-router-page.ts:285
await in value
value @ partial-panel-resolver.ts:211
value @ partial-panel-resolver.ts:82
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
n @ hass-router-page.ts:49
r @ partial-panel-resolver.ts:38
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
C @ lit-element.ts:115
r @ home-assistant-main.ts:47
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165
(anonymous) @ superPropGet.js:6
value @ home-assistant.ts:97
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ home-assistant.ts:225
await in value
value @ home-assistant.ts:82
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:56
_updateHass @ context-mixin.ts:107
(anonymous) @ connection-mixin.ts:279
r @ store.js:19
(anonymous) @ collection.js:27
Promise.then
u @ collection.js:27
l @ collection.js:29
(anonymous) @ collection.js:54
subscribe @ collection.js:99
S @ config.js:16
(anonymous) @ core.ts:121
Promise.then
(anonymous) @ core.ts:112
mushroom.js?hacstag=444350375420:309 🍄 Mushroom 🍄 - 4.2.0
create-element-base.ts:252 card custom:text-divider-row Error: Error in card configuration.
    at tt.setConfig (text-divider-row.js?hacstag=179788256141:187:2392)
    at r (create-element-base.ts:153:11)
    at create-element-base.ts:179:12
    at h (create-element-base.ts:285:12)
    at c (create-element-base.ts:242:12)
    at Module.g (create-card-element.ts:105:3)
    at createThing (vertical-stack-in-card.js?hacstag=142051833050:76:31)
    at VerticalStackInCard.createCardElement (vertical-stack-in-card.js?hacstag=142051833050:99:21)
    at vertical-stack-in-card.js?hacstag=142051833050:25:56
    at Array.map (<anonymous>)
c @ create-element-base.ts:252
g @ create-card-element.ts:105
createThing @ vertical-stack-in-card.js?hacstag=142051833050:76
createCardElement @ vertical-stack-in-card.js?hacstag=142051833050:99
(anonymous) @ vertical-stack-in-card.js?hacstag=142051833050:25
renderCard @ vertical-stack-in-card.js?hacstag=142051833050:25
await in renderCard
(anonymous) @ vertical-stack-in-card.js?hacstag=142051833050:106
Promise.then
element.addEventListener.once @ vertical-stack-in-card.js?hacstag=142051833050:105
n @ fire_event.ts:76
(anonymous) @ create-element-base.ts:198
Promise.then
(anonymous) @ create-element-base.ts:196
h @ create-element-base.ts:285
c @ create-element-base.ts:242
g @ create-card-element.ts:105
createThing @ vertical-stack-in-card.js?hacstag=142051833050:76
createCardElement @ vertical-stack-in-card.js?hacstag=142051833050:99
(anonymous) @ vertical-stack-in-card.js?hacstag=142051833050:25
renderCard @ vertical-stack-in-card.js?hacstag=142051833050:25
await in renderCard
setConfig @ vertical-stack-in-card.js?hacstag=142051833050:17
r @ create-element-base.ts:153
(anonymous) @ create-element-base.ts:179
h @ create-element-base.ts:285
c @ create-element-base.ts:242
g @ create-card-element.ts:105
value @ hui-card.ts:123
(anonymous) @ hui-card.ts:152
n @ fire_event.ts:76
(anonymous) @ create-element-base.ts:198
Promise.then
(anonymous) @ create-element-base.ts:196
h @ create-element-base.ts:285
c @ create-element-base.ts:242
g @ create-card-element.ts:105
value @ hui-card.ts:123
value @ hui-card.ts:42
value @ hui-section.ts:70
(anonymous) @ hui-section.ts:277
value @ hui-section.ts:276
value @ hui-section.ts:198
value @ hui-section.ts:98
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
i @ hui-section.ts:37
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hui-view.ts:109
(anonymous) @ hui-view.ts:338
value @ hui-view.ts:337
value @ hui-view.ts:242
value @ hui-view.ts:156
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
i @ hui-view.ts:62
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hui-root.ts:937
(anonymous) @ hui-root.ts:611
setTimeout
(anonymous) @ render-status.ts:2
requestAnimationFrame
n @ render-status.ts:2
value @ hui-root.ts:611
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
C @ lit-element.ts:115
o @ hui-root.ts:105
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ ha-panel-lovelace.ts:319
await in value
value @ ha-panel-lovelace.ts:170
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
C @ lit-element.ts:115
o @ ha-panel-lovelace.ts:55
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hass-router-page.ts:297
value @ hass-router-page.ts:317
(anonymous) @ hass-router-page.ts:215
Promise.then
value @ hass-router-page.ts:206
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-router-page.ts:285
await in value
value @ partial-panel-resolver.ts:211
value @ partial-panel-resolver.ts:82
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
n @ hass-router-page.ts:49
r @ partial-panel-resolver.ts:38
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
C @ lit-element.ts:115
r @ home-assistant-main.ts:47
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165
(anonymous) @ superPropGet.js:6
value @ home-assistant.ts:97
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ home-assistant.ts:225
await in value
value @ home-assistant.ts:82
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:56
_updateHass @ context-mixin.ts:107
(anonymous) @ connection-mixin.ts:279
r @ store.js:19
(anonymous) @ collection.js:27
Promise.then
u @ collection.js:27
l @ collection.js:29
(anonymous) @ collection.js:54
subscribe @ collection.js:99
S @ config.js:16
(anonymous) @ core.ts:121
Promise.then
(anonymous) @ core.ts:112
apexcharts-card.js?hacstag=331701152212:835  APEXCHARTS-CARD  v2.1.2 
HA-Firemote.js?hacstag=536329656413:8  🔥 FIREMOTE-CARD 🔥  v4.1.3 installed 

```

**Additional information:**

**Comment by ildar170975** [comment]
See no issues:
![image](https://github.com/user-attachments/assets/2b6fd055-f7ea-436c-ab8e-5f1b1d50c4e2)

Chrome 131.0.6778.86 + Win10x64
FF 132.0.2 (64-bit) + Win10x64
2024.11.x

It is clearly said:
"card custom:text-divider-row Error: Error in card configuration."
And you have not posted your code...
